import { Product } from '@/types'

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Silk Elegance Saree',
    slug: 'silk-elegance-saree',
    description: 'A stunning silk saree with intricate golden border work. Perfect for special occasions and celebrations.',
    price: 4500,
    compareAtPrice: 5500,
    images: ['/images/placeholder-product.svg'],
    category: 'Sarees',
    sizes: ['Free Size'],
    colors: ['Red', 'Royal Blue', 'Emerald Green'],
    inStock: true,
    featured: true,
    isNew: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Embroidered Salwar Kameez',
    slug: 'embroidered-salwar-kameez',
    description: 'Beautiful hand-embroidered salwar kameez set with dupatta. Comfortable cotton fabric for daily wear.',
    price: 2800,
    images: ['/images/placeholder-product.svg'],
    category: 'Salwar Kameez',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Pink', 'Sky Blue', 'Lavender'],
    inStock: true,
    featured: true,
    isNew: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Designer Kurti Collection',
    slug: 'designer-kurti-collection',
    description: 'Trendy designer kurti with modern prints and comfortable fit. Perfect for casual outings.',
    price: 1500,
    compareAtPrice: 1800,
    images: ['/images/placeholder-product.svg'],
    category: 'Kurtis',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Mustard', 'Teal', 'Coral'],
    inStock: true,
    featured: true,
    isNew: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Jamdani Cotton Saree',
    slug: 'jamdani-cotton-saree',
    description: 'Traditional Jamdani saree handwoven by skilled artisans. A timeless piece of Bangladeshi heritage.',
    price: 6500,
    images: ['/images/placeholder-product.svg'],
    category: 'Sarees',
    sizes: ['Free Size'],
    colors: ['White & Gold', 'Ivory & Silver'],
    inStock: true,
    featured: false,
    isNew: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Casual Palazzo Set',
    slug: 'casual-palazzo-set',
    description: 'Comfortable palazzo set with printed kurti top. Perfect for everyday wear and college.',
    price: 1200,
    images: ['/images/placeholder-product.svg'],
    category: 'Western',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Navy', 'Wine'],
    inStock: true,
    featured: false,
    isNew: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Bridal Lehenga Choli',
    slug: 'bridal-lehenga-choli',
    description: 'Exquisite bridal lehenga with heavy embroidery and stone work. Make your special day unforgettable.',
    price: 15000,
    compareAtPrice: 18000,
    images: ['/images/placeholder-product.svg'],
    category: 'Bridal',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Red & Gold', 'Maroon & Gold'],
    inStock: true,
    featured: true,
    isNew: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Printed Lawn Three-Piece',
    slug: 'printed-lawn-three-piece',
    description: 'Premium lawn fabric three-piece set with beautiful prints. Includes kameez, shalwar, and dupatta.',
    price: 3200,
    images: ['/images/placeholder-product.svg'],
    category: 'Salwar Kameez',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Peach', 'Mint', 'Rose'],
    inStock: true,
    featured: false,
    isNew: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Georgette Party Wear',
    slug: 'georgette-party-wear',
    description: 'Stunning georgette party wear dress with sequin work. Stand out at every celebration.',
    price: 3800,
    compareAtPrice: 4500,
    images: ['/images/placeholder-product.svg'],
    category: 'Western',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Burgundy', 'Navy'],
    inStock: true,
    featured: true,
    isNew: false,
    createdAt: new Date().toISOString(),
  },
]
